clearwater-cluster-manager.root/usr/share/clearwater/cluster_manager/scripts/load_from_chronos_cluster, clearwater-cluster-manager.root/usr/share/clearwater/cluster_manager/scripts/load_from_chronos_cluster.py
Rob, can you review these new scripts to upgrade to etcd on Chronos.
=> [Reviewer: Rob] Add chronos scripts

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health.py
Rob, can you review these minor fixes to the cluster_health script
=> [Reviewer: Rob] Fix issues in cluster health script

debian/clearwater-etcd.init.d, debian/clearwater-etcd.prerm
Andy, can you review this change to the etcd_name. There's also a fix to remove the monit config on uninstall
=> [Reviewer: Andy] Etcd name

clearwater-etcd/usr/share/clearwater/conf/clearwater-etcd.monit, src/metaswitch/clearwater/cluster_manager/plugin_utils.py
Metaswitch/clearwater-monit#16
=> [No reviewer] Add in groups

src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
=> [Reviewer: Ellie] Pause if a key doesn't exist and we're not going to create it

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health
Tested live on a non-GR system.
=> [Reviewer: Ellie] Quote variables, as they might be missing

clearwater-etcd/etc/logrotate.d/clearwater-etcd, clearwater-etcd/usr/bin/etcdwrapper, debian/clearwater-etcd.init.d, debian/clearwater-etcd.postinst
Fixes #20, should be self-explanatory. Logrotate stuff is copied from the clearwater-diags-monitor logrotate.
=> [Reviewer: Andy] etcd log

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health.py, src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
Small tweaks to make the output of check_cluster_health slightly nicer. 
Also stops config_manager crashing when etcd restarts
=> [Reviewer: Rob] Cluster health script

debian/clearwater-etcd.init.d
Updates to the disaster recovery commands for issues hit when testing
=> [Reviewer: Rob] Updates to disaster recovery docs

debian/.gitignore
Alex,
Please can you review this fix to add your clearwater-management package to .gitignore?
Thanks,
Matt
=> [Reviewer: Alex] Add clearwater-management package to .gitignore

src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
Fixes #51. UTs pass, but I haven't forced any in-service failures of the kind we discussed.
=> [Reviewer: Andy] Detect etcd read failures

cluster_mgr_setup.py, config_mgr_setup.py, shared_setup.py
=> [No reviewer] Add in more packages

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync
Adding a default value for local_site_name
=> [Reviewer: Matt] Default local site

debian/clearwater-etcd.init.d
Remove data dir when removing the member.
=> [Reviewer: Andy] Destroy data dir when removing member

src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py, src/metaswitch/clearwater/cluster_manager/synchronization_fsm.py, src/metaswitch/clearwater/cluster_manager/test/mock_python_etcd.py, src/metaswitch/clearwater/cluster_manager/test/test_base.py, src/metaswitch/clearwater/cluster_manager/test/test_contention.py, src/metaswitch/clearwater/cluster_manager/test/test_new_cluster.py, src/metaswitch/clearwater/cluster_manager/test/test_node_failure.py, src/metaswitch/clearwater/cluster_manager/test/test_resilience.py, src/metaswitch/clearwater/cluster_manager/test/test_scale_down.py, src/metaswitch/clearwater/cluster_manager/test/test_scale_up.py, src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
New fix using quorum instead of consistent. 
Tested live
Fixes #75
=> [Reviewer: Andy] Use quorum on gets/reads

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/plugins/shared_config_plugin.py
=> [Reviewer: Andy] Only stop services that exist

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync
=> [Reviewer: Andy] Add sudo check

src/metaswitch/clearwater/cluster_manager/plugin_utils.py
This retries the monit command if it doesn't work.
Fixes #103
=> [Reviewer: Rob] Retry monit command

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster.py
Only parse lines that have an = in them when loading the memcached config
Fixes #102
=> [No reviewer] Check for =

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py
Cut out the xss echo
Fixes #105
=> [Reviewer: Rob] Defend against JVM_OPTS echo

src/metaswitch/clearwater/cluster_manager/plugin_utils.py
Rob, can you review this change to fix how the cluster manager checks if Cassandra is up. Tested live
Fixes #118
=> [Reviewer: Rob] Iss118

debian/clearwater-etcd.init.d
Andy
As discussed, can you review my proposed change for running etcd as a proxy to talk to an external cluster.  The support is triggered by the existence of an etcd_proxy variable in the configuration (the value doesn't matter - you may object to this!).
I have tested by running a Clearwater system on Docker, with clearwater-etcd on each Clearwater container configured to run etcd as a proxy talking to an etcd cluster on the host OS.
One thing I am uncomfortable about with this is the fact that the function has to make an assumption about the way the etcd nodes in the cluster have been named, in particular that they follow the same convention we've used in clearwater-etcd of naming the nodes using the IP address with dots replaced with dashes.  This coupling isn't great, but I couldn't …
=> [Reviewer Andy] Add support for running etcd in proxy mode talking to an external cluster

.gitignore, Makefile, clearwater-config-manager.root/usr/share/clearwater/infrastructure/alarms/clearwater_config_manager_alarms.json, src/metaswitch/clearwater/config_manager/alarms.py
Rob, can you please review this change to parse the config manager's alarm from a JSON file.
=> [Reviewer: Rob] Parse config manager alarms from file

src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py, src/metaswitch/clearwater/cluster_manager/main.py, src/metaswitch/clearwater/cluster_manager/plugin_utils.py, src/metaswitch/clearwater/cluster_manager/synchronization_fsm.py, src/metaswitch/clearwater/config_manager/etcd_synchronizer.py, src/metaswitch/clearwater/config_manager/main.py
Various changes to fix up the make verify warnings
=> [Reviewer: Rob] Fix up make verify warnings

clearwater-cluster-manager.root/usr/share/clearwater/infrastructure/alarms/clearwater_cluster_manager_alarms.json, clearwater-config-manager.root/usr/share/clearwater/infrastructure/alarms/clearwater_config_manager_alarms.json
Changes to move the cluster/config manager IDs
=> [No reviewer] Alarm ID changes

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/dump_etcd_state, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/force_etcd_state, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_chronos_cluster, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_remote_node_failed, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config, clearwater-etcd/usr/share/clearwater/bin/poll_etcd_cluster.sh, debian/clearwater-etcd.init.d, src/metaswitch/clearwater/cluster_manager/plugin_utils.py
Fix up etcd's use of multiple networks
Pulls in fixes from #112 
Fixes #110
=> [No reviewer] Fix multiple networks

Makefile
Various improvements to the makefile
Fixes #145
=> [No reviewer] Fix makefile

src/metaswitch/clearwater/cluster_manager/plugin_utils.py
Merging unreviewed to get my deployment working, but tagging @eleanor-merry in case I'm missing something (e.g. a name change that hasn't been picked up).
=> [Post-hoc reviewer: Ellie] Use correct poll_cassandra.sh path

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/force_etcd_state
=> [Reviewer: Ellie] Pass key through force_etcd_state

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_chronos_cluster.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster.py
Rob, can you review this change to remove the hard coded node types from the clustering code 
Tested live
=> [Reviewer: Rob] Don't hard code node types into etcd

debian/clearwater-etcd.init.d
=> [No reviewer] Init fixes

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_chronos_cluster, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_chronos_cluster.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster.py, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/plugins/shared_config_plugin.py, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync.py, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config, debian/clearwater-cluster-manager.init.d, debian/clearwater-config-manager.init.d, src/metaswitch/clearwater/cluster_manager/main.py, src/metaswitch/clearwater/cluster_manager/plugin_base.py, src/metaswitch/clearwater/config_manager/etcd_synchronizer.py, src/metaswitch/clearwater/config_manager/main.py, src/metaswitch/clearwater/config_manager/test/test_basic.py, src/metaswitch/clearwater/etcd_shared/plugin_utils.py
This allows the top level key in etcd to be configurable as etcd_key in local_config
=> [Reviewer: Rob] Allow different keys

cluster_mgr_setup.py, config_mgr_setup.py
Add specific pbr dependency
Fixes #176
=> [Reviewer: Rob] Depend on particular pbr version

src/metaswitch/clearwater/cluster_manager/test/test_base.py, src/metaswitch/clearwater/config_manager/test/test_basic.py, src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
Add in 5 second pause if the key doesn't exist in etcd. 
Tested live
Fixes #171
=> [No reviewer] Add in 5 second pause when key doesn't exist

debian/clearwater-etcd.postinst
Andy,
Please can you review this, which fixes #185.  It's pretty trivial, and I've tested live.
Cheers,
Matt
=> [Reviewer: Andy] Restart clearwater-etcd on upgrade

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py, shared_setup.py, src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py, src/metaswitch/clearwater/config_manager/etcd_synchronizer.py, src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py, src/metaswitch/clearwater/etcd_shared/test/mock_python_etcd.py
Andy, can you review this change to stop etcd restarting every hour or so. I've pulled the futures code back in. 
Tested live
Fixes #166
=> [Reviewer: Andy] Iss166

src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py, src/metaswitch/clearwater/cluster_manager/test/dummy_plugin.py, src/metaswitch/clearwater/cluster_manager/test/test_base.py, src/metaswitch/clearwater/cluster_manager/test/test_node_failure.py, src/metaswitch/clearwater/cluster_manager/test/test_scale_down.py, src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py, src/metaswitch/clearwater/etcd_shared/test/mock_python_etcd.py
Rob, can you review these minor fixes that make the unit tests more reliable. This doesn't completely fix the issues with the UTs, but it will hopefully unblock the build
=> [Reviewer: Rob] Some fixes to make the tests more reliable

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed, debian/clearwater-cluster-manager.init.d, src/metaswitch/clearwater/cluster_manager/test/test_base.py, src/metaswitch/clearwater/etcd_shared/test/mock_python_etcd.py
Further fixes to stabilise the UTs (again, this isn't a whole fix)
=> [No reviewer] Further test fixes

clearwater-cluster-manager.root/etc/logrotate.d/clearwater-cluster-manager, clearwater-etcd/etc/logrotate.d/clearwater-etcd
Rob, can you review this change to rotate log files based on size rather than rotating weekly?
Tested live, fixes #190 
I'll make this change to the other logrotate scripts we use as well.
=> [Reviewer: Rob] Change the logrotate settings

clearwater-etcd/usr/share/clearwater/clearwater-etcd/scripts/wait_for_etcd
Script to check that etcd is alive - used for fix in https://github.com/Metaswitch/clearwater-heat/issues/15
=> [Reviewer: Andy] Useful script to check etcd liveness

clearwater-etcd/usr/share/clearwater/bin/poll_etcd.sh
Add --quorum option to poll_etcd (needed for successful chef deployment). 
Tested live
=> [Reviewer: Andy] Add quorum write back

debian/clearwater-cluster-manager.init.d, debian/clearwater-config-manager.init.d
Possibly related to https://github.com/Metaswitch/clearwater-etcd/issues/207
=> [Reviewer: Graeme] Add pidfiles

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
Put failed plugins in their own folder
=> [No reviewer] Move failed plugin folder

clearwater-etcd/usr/share/clearwater/bin/get_etcd_initial_cluster.py, debian/clearwater-etcd.init.d
This moves https://github.com/Metaswitch/clearwater-etcd/pull/225 to be merged into dev.
=> [Reviewer: Ellie] Cope with unstarted etcd nodes

clearwater-config-manager.root/usr/share/clearwater/infrastructure/alarms/clearwater_config_manager_alarms.json
Fixes: https://github.com/Metaswitch/clearwater-etcd/issues/210
=> [Reviewer: Rob] Changed cause of alarm 8500

src/metaswitch/clearwater/etcd_tests/etcdcluster.py, src/metaswitch/clearwater/queue_manager/test/test_fvtests.py
Rob, can you review these fv tests for the queue manager? They use a real etcd cluster, and only run if SLOW=T is set.
=> [Reviewer: Rob] Add queue manager fv tests

cluster_mgr_setup.py, config_mgr_setup.py, queue_mgr_setup.py, shared_setup.py
Pin third party code to a known version
=> [No reviewer] Add explicit version constraints

clearwater-queue-manager.root/usr/share/clearwater/infrastructure/alarms/clearwater_queue_manager_alarms.json
Ellie, please can you actually review the cause, effect and action fields in the whole of this file? I merged the rest of the changes last night because I wanted to merge everything during a quiet period so I didn't disrupt everyone when it all inevitably broke. Thanks!
=> Reviewer EM: Add cause, effect and action to alarms

Makefile, src/metaswitch/clearwater/cluster_manager/alarms.py, src/metaswitch/clearwater/cluster_manager/main.py, src/metaswitch/clearwater/cluster_manager/test/__init__.py, src/metaswitch/clearwater/cluster_manager/test/test_alarms.py, src/metaswitch/clearwater/cluster_manager/test/test_base.py, src/metaswitch/clearwater/config_manager/alarms.py, src/metaswitch/clearwater/config_manager/test/__init__.py, src/metaswitch/clearwater/config_manager/test/test_alarms.py, src/metaswitch/clearwater/config_manager/test/test_basic.py, src/metaswitch/clearwater/etcd_tests/etcdcluster.py, src/metaswitch/clearwater/etcd_tests/etcdtestbase.py, src/metaswitch/clearwater/queue_manager/alarms.py, src/metaswitch/clearwater/queue_manager/etcd_synchronizer.py, src/metaswitch/clearwater/queue_manager/plugin_base.py, src/metaswitch/clearwater/queue_manager/test/__init__.py, src/metaswitch/clearwater/queue_manager/test/test_add_to_queue.py, src/metaswitch/clearwater/queue_manager/test/test_fvtests.py, src/metaswitch/clearwater/queue_manager/test/test_plugin.py, src/metaswitch/clearwater/queue_manager/test/test_remove_from_queue_failure.py, src/metaswitch/clearwater/queue_manager/test/test_remove_from_queue_success.py, src/metaswitch/clearwater/queue_manager/test/test_set_force.py, src/metaswitch/clearwater/queue_manager/test/test_timers.py, src/metaswitch/clearwater/queue_manager/timers.py
This goes with python-common pull request #37.
@eleanor-merry - see also.
=> [Reviewer Adam] Reraise alarms

clearwater-etcd/usr/share/clearwater/conf/clearwater-etcd.monit, clearwater-queue-manager.root/usr/share/clearwater/conf/clearwater-queue-manager.monit
See clearwater-infrastructure for the new script which this uses.
=> [Reviewer Adam] Update clearwater etcd to use new uptime infrastructure.

clearwater-etcd/usr/share/clearwater/conf/clearwater-etcd.monit, src/metaswitch/clearwater/cluster_manager/test/test_alarms.py, src/metaswitch/clearwater/cluster_manager/test/test_base.py, src/metaswitch/clearwater/config_manager/test/test_alarms.py, src/metaswitch/clearwater/config_manager/test/test_basic.py, src/metaswitch/clearwater/etcd_tests/etcdcluster.py, src/metaswitch/clearwater/etcd_tests/etcdtestbase.py, src/metaswitch/clearwater/queue_manager/test/test_add_to_queue.py, src/metaswitch/clearwater/queue_manager/test/test_fvtests.py, src/metaswitch/clearwater/queue_manager/test/test_plugin.py, src/metaswitch/clearwater/queue_manager/test/test_remove_from_queue_failure.py, src/metaswitch/clearwater/queue_manager/test/test_remove_from_queue_success.py, src/metaswitch/clearwater/queue_manager/test/test_set_force.py, src/metaswitch/clearwater/queue_manager/test/test_timers.py
This fixes up some flake8 errors and the PIDfile issue you spotted. Can you please take a look.
=> [Reviewer Ellie] Flake8 errors

debian/clearwater-cluster-manager.init.d, src/metaswitch/clearwater/cluster_manager/main.py, src/metaswitch/clearwater/cluster_manager/plugin_base.py
Plumbing for https://github.com/Metaswitch/chronos/pull/242.
=> [Reviewer: Andy] Plumb through the node's UUID

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config, clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/plugins/apply_config_plugin.py, clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_queue_state.py, clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_restart_queue_state, clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/force_queue_state.py, clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/force_restart_queue_state, clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/modify_nodes_in_queue.py, src/metaswitch/clearwater/queue_manager/plugin_base.py, src/metaswitch/clearwater/queue_manager/queue_fsm.py, src/metaswitch/clearwater/queue_manager/test/test_add_to_queue.py
Fixes https://github.com/Metaswitch/sprout/issues/1375
=> [No reviewer] Fixes merge

debian/clearwater-cluster-manager.init.d, debian/clearwater-config-manager.init.d, debian/clearwater-queue-manager.init.d
Andy,
Please can you review this fix (fixes #294)?  I've tested live.
Matt
=> [Reviewer: Andy] Don't use bash features in sh scripts

debian/clearwater-cluster-manager.postinst, debian/clearwater-config-manager.postinst, debian/clearwater-queue-manager.postinst
Same as https://github.com/Metaswitch/ellis/pull/180.
=> [No review required] Use --always-unzip when installing eggs

Makefile
Discussed with @eleanor-merry .
=> [No reviewer] coverage 4.2 doesn't seem to work for us - pin to the old version

clearwater-etcd/usr/share/clearwater/bin/poll_etcd_cluster.sh
Fix up poll_etcd_cluster to detect cases where the node can't connect to the etcd cluster as a whole, but is up and running itself.
=> [Reviewer: Rob] Extra checks in poll_etcd_cluster

debian/clearwater-cluster-manager.init.d, src/metaswitch/clearwater/cluster_manager/main.py, src/metaswitch/clearwater/cluster_manager/pdlogs.py
Adds cluster_manager_enabled option to make it easy to disable cluster manager.
Tested live.
I'll also update the config options reference.
=> [Reviewer: Adam] Add enabled option

clearwater-cluster-manager.root/usr/share/clearwater/infrastructure/scripts/restart/clearwater_cluster_manager_restart
Needed for the N-site GR upgrade
=> [Reviewer Ellie] Restart cluster manager on changing shared_config

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-bgcf-configuration, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-enum-configuration, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-s-cscf-configuration
Simple scripts to pretty print the contents of the JSON config files
=> [Reviewer: Adam] Pretty print the JSON files

debian/clearwater-queue-manager.init.d, src/metaswitch/clearwater/plugin_tests/test_apply_config_plugin.py, src/metaswitch/clearwater/queue_manager/main.py, src/metaswitch/clearwater/queue_manager/plugin_base.py
This PR plumbs through the override option to be used by the plugins (e.g. in https://github.com/Metaswitch/clearwater-etcd-plugins/pull/6)
=> [Reviewer: Matt] Add override infrastructure

debian/clearwater-etcd.init.d
This touches a file when we've successfully clustered, so that we can then tell the difference between a node that's new, and a node that's been automatically removed from the cluster due to data corruption.
Also fixes up the member ID grep, so that we stop removing arbitrary members of the cluster when we meant to remove ourselves.
=> [Reviewer: Rob] More startup fixes

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_dns_config, debian/clearwater-config-manager.install, src/metaswitch/clearwater/plugin_tests/test_dns_config_plugin.py
=> [Reviewer: Ellie] Add DnsConfigPlugin

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/log_shared_config.py, clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config, debian/control
Logs username and shared_config changes to stdout and syslog on upload_shared_config.
=> [Reviewer: RKD] Audit Logging MVP

debian/clearwater-etcd.init.d
Currently in place on GVD images, so we may hit and test it there. I'll keep my eye out and update if we hit this and it seems good.
Otherwise, as discussed, this is a good thing to do.
=> [Reviewer: Ellie] Remove data dir if failed to join cluster and removing member

debian/clearwater-etcd.init.d
Stop etcd checks from destroying the etcd cluster on an AIO node
=> [No reviewer] Single node etcd cluster

src/metaswitch/clearwater/config_manager/etcd_synchronizer.py, src/metaswitch/clearwater/config_manager/test/test_basic.py, src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
Fixes https://github.com/Metaswitch/clearwater-infrastructure/issues/344 (in conjunction with python-common changes)
=> [Reviewer: Ellie] safely encode non-ASCII content when logging

debian/clearwater-config-manager.install
Merging rel-114-fixes down to dev
=> [No reviewer] Release 114 fixes

debian/clearwater-config-manager.install
Reverting change in https://github.com/Metaswitch/clearwater-etcd/pull/381
=> [No reviewer] Re-instate the dns config plugin

debian/clearwater-etcd.init.d
Remove unused options. Fixes #396
=> [No reviewer] Remove force options from usage statement

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
Don't report site information if we're in a single site deployment. Tested live.
Fix for issue #400
=> [Reviewer: Seb] Don't report site information if we're in a single site deployment

src/metaswitch/clearwater/plugin_tests/test_shared_config_plugin.py
This matches up to https://github.com/Metaswitch/clearwater-etcd-plugins/pull/23
=> [reviewer: seb] Codecs open uts

debian/clearwater-etcd.init.d
Ellie,
If the data directory doesn't exist, then etcd is unable to create it. This prevents etcd from starting correctly.
Simple solution - just create the data directory and make it owned by etcd.
=> [Reviewer: Ellie] Ensure data directory exists and is owned by etcd

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py, clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/modify_nodes_in_queue
This fixes up modify_nodes_in_queue to accept empty values, and fixes up the cluster script to use the correct remote_sites config option. I've also tidied up the output.
Tested live
=> [Reviewer: Seb] Fix up modify and check cluster scripts

fvtest_setup.py, plugins_setup.py
I've pinned the python deps from the files I missed before.
=> Pin previously missed python deps

fvtest_setup.py, plugins_setup.py
Reverts Metaswitch/clearwater-etcd#447
=> Revert "Pin previously missed python deps"

debian/clearwater-config-manager.links
I noticed when looking at the docs that these scripts didn't have the shortcut links. This PR adds them.
=> [Reviewer: Sathiyan] Create clearwater-config-manager.links

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/backup_config
Various fixes to the backup script so that it works, and that it excludes the queue config.
=> [Reviewer: Sathiyan] Fix the backup script

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/backup_config
Merge https://github.com/Metaswitch/clearwater-etcd/pull/451 into the right branch.
=> Merge master into dev

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
Rename remote_site_names to site_names
=> [Reviewer: Seb] Change name to site_names

clearwater-cluster-manager.root/usr/share/clearwater/conf/clearwater-cluster-manager.monit, clearwater-config-manager.root/usr/share/clearwater/conf/clearwater-config-manager.monit, clearwater-etcd/usr/share/clearwater/conf/clearwater-etcd.monit, clearwater-queue-manager.root/usr/share/clearwater/conf/clearwater-queue-manager.monit
As per https://github.com/Metaswitch/sprout/pull/1863
=> [No reviewer] Don't wait for 6 cycles before killing a process

src/metaswitch/clearwater/plugin_tests/test_apply_chronos_shared_config_plugin.py, src/metaswitch/clearwater/plugin_tests/test_chronos_shared_config_plugin.py
=> [No reviewer] Rename chronos file

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py, src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Reverts Metaswitch/clearwater-etcd#470
=> Revert "[Reviewer: Krista] Use subprocess call without shell"

Makefile, clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py, src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Hi Andy this pull request is to replace https://github.com/Metaswitch/clearwater-etcd/pull/470 after you pointed out the shlex usage wouldn't work. Would you pls check if the current version is fine?
=> Use subprocess call without shell

Makefile
Fix the Makefile target so that it correctly depends on the alarm constants file.
=> [No reviewer] Correct python component generation

Makefile, debian/clearwater-cluster-manager.postinst, debian/clearwater-config-manager.postinst, debian/clearwater-queue-manager.postinst
Exploit the changes in https://github.com/Metaswitch/python-common/pull/113
=> [Reviewer: Seb] Install later version of pip and wheel

clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/cw-config
=> Fixing bogus comment

Makefile
Match https://github.com/Metaswitch/ellis/pull/223
=> [No reviewer] Only rebuild the common wheel if it's been cleaned

clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/modify_nodes_in_queue.py, debian/clearwater-cluster-manager.postinst, debian/clearwater-config-manager.postinst, debian/clearwater-queue-manager.postinst
See commit text for details.
I've tested the code live using a debian package installed on the box.
=> Fix for #2624

debian/clearwater-cluster-manager.links, debian/clearwater-config-manager.links
=> Bpa scripts

src/metaswitch/clearwater/config_manager/config_access.py
Putting correct facility in config change audit logs.
=> [MD6: review] Ensure audit logs are sent with correct facility

debian/clearwater-cluster-manager.init.d, debian/clearwater-config-manager.init.d, debian/clearwater-etcd.init.d, debian/clearwater-queue-manager.init.d
Use exit rather than return to avoid worrying error message.
=> [Reviewer: Krista] Fix up worrying error on decommission

src/metaswitch/clearwater/config_manager/config_access.py, src/metaswitch/clearwater/config_manager/config_type_class_plugin.py, src/metaswitch/clearwater/config_manager/test/test_config_access.py, src/metaswitch/clearwater/config_manager/test/test_config_type.py
Allow streaming of large changes to remote server
Use unified diffs for JSON/xml
=> Fix up config diff errors 

config_mgr-requirements.txt, src/metaswitch/clearwater/config_manager/config_type_class_plugin.py
Add json schema as a requirement for the config manager
=> [Reviewer: Adam] Allow JSON config upload in Project Clearwater

clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py, src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
secure load
sha512 instead of md5
=> Bandit final
