- debian/clearwater-etcd.init.d
- debian/rules
Can you review this change to stop clearwater-etcd from starting if there's no etcd_cluster setting, rather than crashing.
> [Reviewer: Andy] Allow empty etcd_cluster

- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/cluster_manager/plugin_utils.py
Largely discussed live test fixes. Unclustering cassandra is now much quicker; however there is still a lengthy wait after the cassandra is removed from the cluster before quiescing the node finishes.
@eleanor-merry may be interested too
> Reviewer RKD: Live test fixes

- debian/clearwater-etcd.init.d
- debian/clearwater-etcd.postinst
This:
* differentiates between the "listen IP" and the "advertisement IP", potentially allowing us to advertise EC2 public IPs in future
* defaults both to $management_local_ip
> [Reviewer: Andy] Traffic separation

- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/cluster_manager/plugin_loader.py
This fixes the issue you were seeing on Sprout - the etcd key for the remote memcached site didn't exist, and we didn't set the last cluster view in this case, so we always saw that the last view (None) didn't match the result ({}) and kept reading in a loop. (In any other plugin, we'd have moved ourself into the cluster and this wouldn't have happened, but remote memcached is special.)
I'm not sure this is the right fix - it might be nicer to have `load_as_plugin` for this plugin return None if the remote site isn't set (and for the plugin loader to spot that). I'll mull it over, but this unblocks you.
> [Reviewer: Ellie] Don't tight-loop if the etcd key doesn't exist

- debian/clearwater-cluster-manager.init.d
- src/metaswitch/clearwater/cluster_manager/main.py
This:
* logs at INFO level by default, as originally specced
* suppresses urllib3 WARNING logs, which are currently a bit spammy (I can see why - connections aren't closed when they time out, so a connection with a pending response gets reused and immediately fails - but we'll have to submit a patch to urllib3 to fix it properly)
> [Reviewer: Andy] Clean up logging

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health.py
Tested a version of this live, output:
```
Describing sprout memcached cluster in site odd_numbers:
Local node is in this cluster
Cluster is healthy and stable
10.101.147.26 is in state normal
Describing sprout memcached cluster in site even_numbers:
Local node is *not* in this cluster
Cluster is healthy and stable
10.7.139.4 is in state normal
Describing sprout chronos cluster in site odd_numbers:
Local node is in this cluster
Cluster is healthy and stable
10.101.147.26 is in state normal
```
It doesn't work with Cassandra yet - I'd agreed with Andy to add a /clearwater/ prefix to the keys, but haven't done that for Homestead/Memento's Cassandra plugins. I'll fix those plugins up.
> [Reviewer: Ellie] Update check_cluster_health to work again and support GR

- clearwater-etcd/usr/bin/clearwater-etcdctl
Rob, please can you review this change to add a wrapper script around etcdctl that fills in the local IP based on /etc/clearwater/config. 
I've tested this by running `clearwater-etcdctl member list` when:
* `local_ip` was set up correctly. 
* `local_ip` was wrong but `management_local_ip` was correct.
Both times the script returned the expected output.
> [Reviewer: Rob] Add a wrapper script around etcdctl

- debian/clearwater-etcd.init.d
This fix removes the etcd member from the list if it's present before trying to rejoin the cluster. 
Tested live
> [Reviewer: Andy] Remove from list when joining

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
Fixes #28. I'll test by installing on a node, running it, and checking ther dump_etcd_state output before and afterwards.
> [Reviewer: Alex] Make mark_node_failed script more usable

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health
I've run `grep -r "local_site_name" src/ clearwater-cluster-manager.root/ debian/*.init.d` to check that every script that uses it also defaults it.
> [Reviewer: Ellie] Default local_site_name in check_cluster_health

- Makefile
- debian/control
This PR adds a new meta-package that depends on the cluster and config managers, so that operators only need to install one thing. 
Tested by:
* On a new system running `sudo apt-get install clearwater-management`. Both dependent packages got installed. 
* Doing a new build of this repo and running `sudo apt-get update && sudo apt-get install clearwater-management`. The meta-package and both dependent packages were upgraded.
> [Reviewer: Matt] Add config-management meta-package

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/plugins/shared_config_plugin.py
I picked up the latest code out of master and it didn't work.  It looks like `plugin_utils.py` has been moved into `etcd_shared`, but the references here and in sprout haven't been updated.
> [Reviewer: Andy] Fix path to plugin_utils

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_health
`check_cluster_health` didn't work in a non-GR deployment because `remote_site_name` isn't set but `set -u` is (so bash considers accessing undefined variables as an error).
> [Reviewer: Andy] Fix check_cluster_health script when running non-GR

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
- debian/clearwater-config-manager.init.d
`upload_shared_config` is missing a `local_site_name`.  Fix is to default it as we do everywhere else.
> [Reviewer: Andy] Default local_site_name in upload_shared_config

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_chronos_cluster
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster
This quotes any variables that might be missing (matching fix to https://github.com/Metaswitch/clearwater-etcd/commit/389cf7c028c25b6a5ba7973b38178829c2fbbaa8)
I've also checked the other load_from* scrips. 
Part of the fix for https://github.com/Metaswitch/sprout/issues/1055
> [Reviewer: Matt] Add in quotes

- .gitignore
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync.py
You saw this earlier today (and saw me put in this very fix).
> Reviewer Alex - Load plugin_utils from etcd_shared, not config_manager

- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
A really simple fix to a typo in the cluster manager (that was causing the cluster manager to crash).
> [Reviewer: Andy] Fix typo in cluster manager

- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/cluster_manager/plugin_utils.py
- src/metaswitch/clearwater/config_manager/__init__.py
- src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/config_manager/main.py
This means we don't use a timeout on etcd watches. Watching doesn't block termination, so we can just use an eternal watch. Tested live. 
I've also tidied up some flake8 warnings
Fixes #33
> [Reviewer: Andy] Iss33

- .gitignore
- debian/clearwater-config-manager.init.d
- debian/clearwater-etcd.init.d
This adds a random sleep before joining an existing cluster. Tested live. 
Fixes #71
> [Reviewer: Andy] Add in sleeps

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/plugins/shared_config_plugin.py
- debian/clearwater-cluster-manager.init.d
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/cluster_manager/plugin_base.py
- src/metaswitch/clearwater/cluster_manager/plugin_utils.py
- src/metaswitch/clearwater/cluster_manager/test/contention_detecting_plugin.py
- src/metaswitch/clearwater/cluster_manager/test/dummy_plugin.py
- src/metaswitch/clearwater/cluster_manager/test/fail_partway_through_plugin.py
- src/metaswitch/clearwater/cluster_manager/test/plugins/plugin_loader_test_plugin.py
- src/metaswitch/clearwater/etcd_shared/plugin_loader.py
- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Andy please can you review this PR that allows clustering to work with multiple networks. 
The bulk of the PR is refactoring so plugins are passed parameters in a class object rather than one by one. - this will make it easier to add new parameters in future. Using this new framework, the cluster-manager now passes plugins the signaling namespace which the Cassandra plugins can use to decommission Cassandra. 
I have tested this as follows:
* Created a FT deployment, and checked that all nodes were clustered together (using `check_cluster_health`) and all nodes had the shared config. 
* Successfully decommissioned a homestead node (that did not use multiple networks). 
* On a homer node I set up an aliased network namespace and set that as `signaling_namespace`. Then I successfully …
> [Reviewer: Andy] Enable cassandra clustering to cope with multiple networks. 

- src/metaswitch/clearwater/cluster_manager/plugin_utils.py
Easy fix for Cassandra not dying, I've not managed to repro the failure with or without this fix, but this should always be safe.
Fixes https://github.com/Metaswitch/clearwater-cassandra/issues/27.
> Reviewer Ellie - Kill the Cassandra PID in case service stop doesn't work

- debian/clearwater-cluster-manager.init.d
My cool one-liner with &&s somehow meant that "return 2" didn't take effect.
Tested as follows:
```
[ralf-1]ubuntu@ec2-54-160-232-37:~$ cat test_ncm.sh
do_start() {
if [ -e /etc/clearwater/no_cluster_manager ]
then
echo "/etc/clearwater/no_cluster_manager exists, not starting cluster manager"
return 2
fi
echo "abcd"
}
do_start
[ralf-1]ubuntu@ec2-54-160-232-37:~$ bash test_ncm.sh
/etc/clearwater/no_cluster_manager exists, not starting cluster manager
[ralf-1]ubuntu@ec2-54-160-232-37:~$
```
> [Reviewer: Ellie] Actually exit if no_cluster_manager exists

- Makefile
- cluster_mgr_setup.py
- config_mgr_setup.py
- debian/clearwater-cluster-manager.postinst
- debian/clearwater-config-manager.postinst
Fixes #81 - this means we install the .egg file we want, which pulls in the other dependencies, rather than installing every .egg file in the directory.
Tested on a 14.04 node by confirming that `git clone -b 1404_fix --recursive https://github.com/Metaswitch/clearwater-etcd.git iss81_test && cd iss81_test && make deb` works and `git clone --recursive https://github.com/Metaswitch/clearwater-etcd.git iss81_test_2 && cd iss81_test_2 && make deb` consistently fails.
> [Reviewer: Andy] Change easy_install command to be more precise

- cluster_mgr_setup.py
- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/cluster_manager/test/mock_python_etcd.py
Catches SIGTERMs and shuts plugins down appropriately, and makes sure that we don't wait forever when we get a SIGTERM in the middle of an etcd watch.
Tested by:
* installing clearwater-cluster-manager on Ellis and checking it doesn't constantly restart
* running `service clearwater-cluster-manager stop` on Sprout and confirming (from the logs) that it exited cleanly and quickly
Fixes #33 and #37.
> [Reviewer: Ellie] Fix quitting

- clearwater-etcd/usr/bin/etcdwrapper
- clearwater-etcd/usr/share/clearwater/bin/poll_etcd.sh
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/cluster_manager/pdlogs.py
- src/metaswitch/clearwater/cluster_manager/plugin_base.py
- src/metaswitch/clearwater/cluster_manager/synchronization_fsm.py
- src/metaswitch/clearwater/config_manager/alarms.py
- src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/config_manager/main.py
- src/metaswitch/clearwater/config_manager/pdlogs.py
Note that:
* the NOT_YET_CLUSTERED_ALARM log will be created by plugins
* I've added a cluster_description method to plugins (returning something like 'remote memcached cluster') and will add that to all existing plugins
> [Reviewer: Ellie] Add ENT logs to cluster-manager and config-manager

- debian/clearwater-cluster-manager.init.d
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/cluster_manager/plugin_base.py
- src/metaswitch/clearwater/cluster_manager/plugin_utils.py
- src/metaswitch/clearwater/config_manager/main.py
Key changes are:
* clearwater-cluster-manager needs to know both the signalling and management IPs, so pass both in
* clearwater-cluster-manager can't connect to Cassandra directly due to network namespaces, so it needs to use /usr/share/clearwater/bin/poll-tcp for that
* (slightly unrelated) clearwater-cluster-manager was specced as logging at INFO level by default, as it's not on the call path and these logs are useful. I previously did that by having `log_level=3` in the init.d script, but explicitly setting `log_level=2` breaks that, so I've changed it to translate 2 to INFO level.
These are fixes for #110 .
> [Reviewer: Andy] Traffic separation fixes

- src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
Rob,
This change means that if the config key is absent in `etcd` then we'll wait for it to arrive rather than tight-loop polling.  Tested live, including restarting `clearwater-config-manager` when the key is missing, checking it sits in "Waiting for changes" then when I upload the shared config, it spots that change and processes it.
> Reviewer Rob - Don't tight loop on missing config

- Makefile
- src/metaswitch/clearwater/cluster_manager/test/test_node_failure.py
- src/metaswitch/clearwater/cluster_manager/test/test_scale_down.py
I hit two issues when setting up clearwater-etcd on 14.04:
* The UTs didn't run. This was because we install the .egg files into the development virtualenv - on 12.04 this is OK, but in 14.04 this seems to mean that you can't see the 'test' directory (which is only in the local system, not the egg). Fix is to not install the .egg files and just set PYTHONPATH appropriately.
* Once the UTs ran, they didn't terminate. This was because I hadn't cleaned up a couple of EtcdSynchronizers, so their background thread was still running.
> [Reviewer: Alex] 14.04 fixes

- README.md
https://github.com/Metaswitch/clearwater-etcd/commit/0df3c13b26ae356bc0962b1194dd6cd51ad95ba9 removed the need to supply `home_domain` in `local_config`.  This change just updates the README to match.
> Reviewer Alex - Remove home_domain reference in README

- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/config_manager/main.py
Previously, we attempted to join threads one at a time - so if thread 2 threw an exception, we wouldn't catch that and restart until thread 1 joined (potentially a very long time). This restructures things so that if any thread throws an exception, we'll spot it as soon as we can.
Not tested at all.
> [Reviewer: Andy] Attempt to join all threads regularly

- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/config_manager/main.py
See the comment at https://github.com/Metaswitch/clearwater-etcd/compare/etcd_invalid_index?expand=1#diff-420c3a9c99bb96c4ca6213ef1e154c0cR148 for the basis of the change.
I'm going to test by hacking init.d to set the `--snapshot-count 5` option to etcd to force ludicrously frequent snapshots, spin up a deployment, check it's usable, and check that I've seen my new log (and that we've subsequently recovered from this state).
If that test doesn't hit this error condition, I can't see another good way to test it, so might just have to merge as-is.
> [Reviewer: Andy] Cope with etcd index failures

- clearwater-etcd/usr/share/clearwater/bin/poll_etcd.sh
This updates the poll_etcd script so that attempts to write a key to etcd rather than just check that etcd is listening on a port
Fix taken from #126
> [No reviewer] Update poll_etcd script

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
This stops the output of upload_shared_config being just sent to dev/null
Fixes #98
> [Reviewer: Rob] Fix up logging from upload_shared_config

- shared_setup.py
- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/cluster_manager/test/test_base.py
- src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
- src/metaswitch/clearwater/etcd_shared/test/mock_python_etcd.py
Having an eternal watch means that the python-etcd client will miss updates (it sticks watching on an old index). I'm reverting the futures fix (which means we'll still hit #166) for now
> [No reviewer] Revert eternal watch

- src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
As discussed, this stops urllib from re-using a TCP connection after timing out an HTTP connection over it.  Implemented as a monkey-patch for now, we'll investigate sending the fix upstream too.  I've also upped the etcd logging level (it's not too spammy and the logs might be useful for debugging).
Fixes #166 (and #33 again) without pulling in the futures work.
Tested live.
> Reviewer Rob - Close timed out connections in urllib3

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/plugins/shared_config_plugin.py
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/apply_shared_config
Rob, can you review this change to add an optional --sync option to apply_shared_config. If this is set then we wait for the services to restart before exiting
Tested live, fixes #129
> [Reviewer: Rob] Iss129

- clearwater-etcd/usr/share/clearwater/bin/poll_etcd.sh
Change behaviour of the poll_etcd script to read stats values from etcd, rather than write a test "liveness-check" key. The reason why the write check needs to be reworked is that the write will fail if the cluster is non-quorate, so monit will repeatedly kill etcd on each healthy node if the cluster is in this state, making it harder to diagnose the fault with the cluster and potentially impacting the ability of the cluster to recover from the condition.
The stats read succeeds if the cluster is non-quorate, and is still a check that the etcd process is responsive.
Tested against quorate and non-quorate clusters.  The script has also been tested against a non responsive etcd cluster (by temporarily changing the script to point at port 2380 rather than 4000 so that the stat request won't …
> Reviewer AMC: Read stats rather than write values in poll etcd

- src/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py
Alex, can you review this fix to stop scale downs from getting stuck in the 'waiting to leave' state. The problem was that there was a race condition where:
* leave_cluster sets the leaving_flag to true, then attempts to write the 'waiting to leave' state into etcd. 
* after it has successfully written to etcd it sets the leaving flag to false. 
* writing to etcd triggers the main etcd_synchronizer starts processing again though, so at the same time the main process is checking whether the leaving_flag is true, and if so just writes 'waiting_to_leave' into etcd and doesn't go into the FSM.
* if we hit this then it's broken from this point as we then never enter the FSM again as the old and new values are the same
Tested live, fixes #204
> [Reviewer: Alex] Fix waiting to leave hang

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
Alex, can you review this change to use a specific cassandra plugin in mark_node_failed. This plugin removes the cassandra node from the cassandra cluster (using nodetool removenode).
This change means that you have to run mark_node_failed on a node that has cassandra installed to remove a cassandra node - I'll update the documentation with this.
Tested live, fixes #205
> [Reviewer: Alex] Add cass plugin to mark node failed

- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Stops the command being appended to itself when running cluster manager in multiple networks
Fix for https://github.com/Metaswitch/clearwater-cassandra/issues/58.
> [Reviewer: Matt] Fix namespace command

- src/metaswitch/clearwater/cluster_manager/alarms.py
Extra diagnostics, which are worth having in light of https://github.com/Metaswitch/clearwater-etcd/issues/212.
> [Reviewer: Alex] Improve logging around the progress of the TOO_LONG_CLUSTERING alarm

- src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
Fixes https://github.com/Metaswitch/clearwater-etcd/issues/169 (following guidance in https://docs.python.org/2/howto/unicode.html#python-2-x-s-unicode-support), and sets errors="replace" so we don't get exceptions on non-UTF8 characters.
> [Reviewer: Graeme] Translate UTF-8 files to a series of bytes for MD5 encoding

- debian/clearwater-cluster-manager.init.d
- debian/clearwater-config-manager.init.d
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/config_manager/main.py
Fixes https://github.com/Metaswitch/clearwater-etcd/issues/218 along with https://github.com/Metaswitch/python-common/pull/31. I've tested live:
```
/var/log/clearwater-cluster-manager/cluster-manager_20151027T170000Z.txt:27-10-2015 17:38:32.560 UTC INFO utils.py:411 (thread MainThread): Acquired exclusive lock on /var/run/clearwater-cluster-manager.pid
/var/log/clearwater-cluster-manager/cluster-manager_20151027T170000Z.txt:27-10-2015 17:38:42.055 UTC ERROR utils.py:413 (thread MainThread): Lock on /var/run/clearwater-cluster-manager.pid is held by another process
/var/log/clearwater-cluster-manager/cluster-manager_20151027T170000Z.txt:27-10-2015 17:38:57.978 UTC ERROR utils.py:413 (thread MainThread): Lock on /var/run/clearwater-cluster-manager.pid is held by another process …
```
> [Reviewer: Alex] Lock the PIDfile, to prevent multiple processes running at once

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/apply_shared_config
apply_shared_config directly needs root permissions, so exit with a useful error if we don't have them
> [Reviewer: Rob] Add root permissions check

- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
https://github.com/Metaswitch/clearwater-etcd/pull/223 had one slight side-effect - it set all the etcd-managed file permissions to 0600. This sets them to a more normal 0644.
> [Reviewer: Ellie] Set etcd-managed files to have 0644 permissions, not 0600

- cluster_mgr_setup.py
- config_mgr_setup.py
- debian/clearwater-cluster-manager.init.d
- debian/clearwater-config-manager.init.d
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/config_manager/main.py
This PR:
* deletes the places where the init script would delete the pidfile without locking it
* renames the process from "python" to "cw-cluster-mgr" or "cw-config-mgr" - not for start-stop-daemon purposes, but for diagnostics
* adds prctl as a dependency
(We already created and used a pidfile for monitoring, and there are no subprocesses.)
> [Reviewer: Matt] Don't remove pidfiles without a lock, and set the process name with prctl

- clearwater-queue-manager.root/usr/share/clearwater/conf/clearwater-queue-manager.monit
- src/metaswitch/clearwater/queue_manager/plugin_base.py
Use the queue manager alarm. Also fix up the global alarm text. 
Tested live
Fixes #251
> [Reviewer: Graeme] Use correct alarm

- src/metaswitch/clearwater/config_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/queue_manager/etcd_synchronizer.py
- src/metaswitch/clearwater/queue_manager/queue_fsm.py
Graeme, can you review these fixes to improve the stability of the queue manager
The fixes:
* Stop the config manager from adding the node to the queue if the config file hasn't changed
* Make sure that the timers are cleared before reuse
* Stop a local state action from being repeated
Tested live
These fixes are linked to #249
> [Reviewer: Graeme] Stop restarting so often and fix timers

- debian/clearwater-cluster-manager.postinst
- debian/clearwater-cluster-manager.prerm
- debian/clearwater-cluster-manager.triggers
- debian/clearwater-config-manager.postinst
- debian/clearwater-config-manager.prerm
- debian/clearwater-config-manager.triggers
- debian/clearwater-etcd.postinst
- debian/clearwater-etcd.prerm
- debian/clearwater-etcd.triggers
- debian/clearwater-queue-manager.postinst
- debian/clearwater-queue-manager.prerm
- debian/clearwater-queue-manager.triggers
Changes to the cluster manager to use the alarm agent trigger (see https://github.com/Metaswitch/clearwater-snmp-handlers/pull/119) and remove the user/logs on uninstall (part of the fix for #247)
If this is OK, I'll do the same changes to every other repo (woo!)
> [Reviewer: Andy] Fix up cluster managers postinst/prerm

- debian/clearwater-etcd.init.d
Deals with the case where the etcd_cluster variable contains spaces
Fixes #237
> [No reviewer] Replace commas with whitespace

- debian/clearwater-etcd.init.d
For example, don't match 1.2.3.40 when looking for 1.2.3.4.
Check for non-word characters around the IP address.
> Be more careful matching IP addresses

- debian/clearwater-etcd.init.d
There's another place in the same file that might use the word-delimitation fix. `10-67-79-1 != 10-67-79-10`
> Be careful when grepping for IPs in another place

- clearwater-etcd/usr/bin/etcdwrapper
- debian/clearwater-etcd.init.d
- debian/clearwater-etcd.postinst
- debian/clearwater-etcd.prerm
Can you review this fix to https://github.com/Metaswitch/clearwater-etcd/issues/262? Essentially, because we don't build etcd ourselves, I've done the pidfile locking stuff we normally do in C/Python code in a Bash wrapper script instead.
As this is Bash magic, you seemed like the best reviewer - shout if you're too busy.
> [Reviewer: Matt] Lock etcd's pidfile before we write to it

- clearwater-etcd/usr/share/clearwater/conf/clearwater-etcd.monit
- clearwater-queue-manager.root/usr/share/clearwater/conf/clearwater-queue-manager.monit
Use check-uptime to clear alarms and avoid suprious monit failures.
> [Reviewer: None] Use updated check-uptime script.

- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Remember that bug we hit where bono quiescing held the clearwater-queue-manager PID lock?
I hit it again, and figured out how to stop spawned processes holding the PID lock.
> [Reviewer: Graeme] Don't pass PID lock to child processes

- src/metaswitch/clearwater/cluster_manager/plugin_base.py
- src/metaswitch/clearwater/cluster_manager/synchronization_fsm.py
This adds the on_startup method we discussed in https://github.com/Metaswitch/clearwater-cassandra/pull/79#commitcomment-16538138.
> [Reviewer: Alex] Add on_startup method

- clearwater-etcd/usr/share/clearwater/conf/clearwater-etcd.monit
- clearwater-etcd/usr/share/clearwater/infrastructure/scripts/check-etcd-uptime
- clearwater-queue-manager.root/usr/share/clearwater/conf/clearwater-queue-manager.monit
- clearwater-queue-manager.root/usr/share/clearwater/infrastructure/scripts/check-queue-manager-uptime
Monit can't pass arguments to check-program scripts in its current version.
> [Reviewer: None] Cope with Monit restrictions

- debian/clearwater-etcd.init.d
Fixes #262 - I think for real this time.
I've run the following script:
```
for i in {1..150}
do
service clearwater-etcd restart &
done
```
which reliably reproduced the issue before this fix and doesn't do so afterwards.
I've also checked that there are no other instances of `--make-pidfile` in the init.d script.
> [Reviewer: Ellie] Don't let start-stop-daemon create the pidfile without taking a lock

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/plugins/apply_config_plugin.py
- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_queue_state.py
- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_restart_queue_state
- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/force_queue_state.py
- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/force_restart_queue_state
- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/modify_nodes_in_queue.py
- src/metaswitch/clearwater/queue_manager/plugin_base.py
- src/metaswitch/clearwater/queue_manager/queue_fsm.py
- src/metaswitch/clearwater/queue_manager/test/test_add_to_queue.py
Various stability fixes for the queue-manager
* shared_config changes picked up by all nodes (including the one that ran upload_shared_config)
* Increased the time allowed for a node to start up (to cover the case where homestead takes just over 5mins on a clean install)
* Added in some missing scripts
* Trimmed out some spammy logs
> [Reviewer: Adam] Etcd stability fixes

- src/metaswitch/clearwater/cluster_manager/synchronization_fsm.py
Fixes #289.
I've tested by spinning up a GR deployment with 2 Ralfs in each site. Without this change, the TOO_LONG_CLUSTERING alarm was raised after 15 minutes on all the nodes. With this change, the alarm wasn't raised.
@JimBunch I'm going to merge into release-94-fixes once this is reviewed - is that ok? I'll leave it up to you whether you want to take a new build with it.
> Reviewer RKD: Don't trigger TOO_LONG_CLUSTERING alarm if we're not in the cluster

- debian/clearwater-cluster-manager.init.d
- debian/clearwater-config-manager.init.d
- debian/clearwater-queue-manager.init.d
As discussed, most of our processes refuse to start until shared config has been provided.  This brings `clearwater-*-manager` into consistent behaviour (but with local_config rather than shared).
This makes it possible to add config after installing the software (e.g. to make images).
> Reviewer Ellie - Prevent starting before ready

- src/metaswitch/clearwater/cluster_manager/main.py
The usage needs to be on a single line for this to work. [I can't remember why exactly].
> [Reviewer: GDR] Fix bugs from merging dev into split-clusters.

- clearwater-etcd/usr/share/clearwater/bin/poll_etcd.sh
When we are a proxy, we won't be listed in /v2/stats/self. We don't actually care what node is listed at this point, we just need one to be.
As such, we change what we look for in the results from `"name":"{local_ip}"` to `"name":"` when we are configured as a proxy (i.e. etcd_cluster is blank).
Without this fix, when configured as a proxy, monit will continually restart etcd.
I've tested this by spinning up a deployment with proxies and verifying they don't get killed, and manually running the script on both master and proxy nodes to ensure it's doing the right thing.
> [Reviewer: AJH] Fix polling for health when configured as a proxy

- debian/clearwater-etcd.init.d
Alex,
Currently etcd_proxy takes a comma separated list of addreses in the form `<name>=<peer url>`. We'd like it to also be able to instead take a comma separated list of IP addresses, in the same fashion as etcd_cluster.
This enhances the init.d script to detect which one it has been provided, and provide it to etcd as appropriate.
> [Reviewer: AJH] Allow etcd proxy nodes to be configured using IPs

- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_node_health.py
- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
The issue seen was that nodes would drop into the failed state in the queue-manager queue very quickly after starting the processing step. 
The telling section of the queue-manager logs stated:
```
21-07-2016 15:50:52.233 UTC ERROR plugin_utils.py:70 (thread ApplyConfigPlugin): Command /usr/share/clearwater/clearwater-queue-manager/scripts/check_node_health.py failed with return code 1 and printed output 'Cannot create socket to [localhost]:2812 -- Connection refused
```
Looking at the check_node_health script, the subprocess.check_output call can raise a CalledProcessError exception that is only then caught once we have dropped out of the run loop, meaning that a single exception will kick us out of the retry for 450 seconds stage. 
Catching the error in place, and returning that call's …
> [Reviewer: Ellie] Catch socket connection error

- Makefile
Pinning the version of setuptools installed to 24. 
Probably as in https://github.com/Metaswitch/crest/pull/293 , version 25 is causing some issues. 
I was seeing issues when running `make test`, getting the following error output:
```
Installed /tmp/easy_install-wqmOnn/mock-2.0.0/pbr-1.10.0-py2.7.egg
Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
ERROR:root:Error parsing
Traceback (most recent call last):
File "/tmp/easy_install-wqmOnn/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
attrs = util.cfg_to_args(path, dist.script_args)
File "/tmp/easy_install-wqmOnn/mock-2.0.0/pbr-1.10.0-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
kwargs = …
```
> [Reviewer: Ellie] Pin to setuptools 24

- README.md
- debian/clearwater-etcd.init.d
This fixes #293 - see my notes in that issue, particularly https://github.com/Metaswitch/clearwater-etcd/issues/293#issuecomment-244342613, for more information.
I'm planning to test by:
* just spinning up a normal deployment and checking that it works
* forcing a node into 'unstarted' state (probably by commenting out https://github.com/Metaswitch/clearwater-etcd/blob/dev/debian/clearwater-etcd.init.d#L304 so that 'member add' runs but etcd doesn't start) and checking that the code to recover from that state hasn't broken due to my refactoring of it
* uploading the two broken etcd data directories you captured as part of #293 to a node, starting etcd, and confirming that it deletes the data directories and rejoins the cluster in both cases
> [Reviewer: Matt] Use etcd-dump-logs to detect and recover from data dir corruption

- src/metaswitch/clearwater/config_manager/main.py
- src/metaswitch/clearwater/config_manager/test/test_basic.py
- src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
- src/metaswitch/clearwater/queue_manager/main.py
- src/metaswitch/clearwater/queue_manager/test/test_base.py
Fixes #317 by wrapping the plugin thread entry point in a try/except branch.
I did the following testing...
* I added a line in `on_config_changed` in `shared_config_plugin.py` to always raise an IOError on Sprout-1.
* I changed `shared_config` on one of my nodes and the exception was raised. Details of the exception were logged to `config-manager.output.log`. The `clearwater-config-manager` process continued to run. Next time I changed `shared_config` nothing happened because the shared config plugin thread was dead.
* I upgraded Sprout-1 to include my fix. Now when the process was restarted the exception was caught, a nice stack trace was printed in the normal config file, and the process was killed. (Monit then restarted the process and it happened again because I was still raising the …
> Reviewer EM: Catch exceptions in plugins

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/recreate_cluster
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/recreate_cluster.py
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/recreate_homestead_cluster
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/recreate_sprout_cluster
- clearwater-etcd/usr/share/clearwater/clearwater-etcd/scripts/load_etcd_config
- clearwater-etcd/usr/share/clearwater/clearwater-etcd/scripts/load_etcd_config.py
- clearwater-etcd/usr/share/clearwater/clearwater-etcd/scripts/save_etcd_config
- clearwater-etcd/usr/share/clearwater/clearwater-etcd/scripts/save_etcd_config.py
The scripts needed for the N-Site GR upgrade.
We only need 3, because the existing load_from_*_cluster scripts should work fine for populating etcd with the cluster info after merging Sprout and Ralf Chronos/memcached clusters
Testing done: manual testing that the correct etcd config is copied/saved/loaded
> [Reviewer: Ellie] Add etcd scripts for N-site GR upgrade

- src/metaswitch/clearwater/plugin_tests/test_apply_config_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_shared_config_plugin.py
The Queue/Config manager plugins aren't created with parameters when they're used, so don't create them with parameters in the UTs
> [Reviewer: Adam] Remove parameters from tests

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/backup_config
Rob,
This fixes a bug where we fail to correctly back up the configuration.
> [Reviewer: RKD] Fix Backup failure

- debian/clearwater-etcd.init.d
This PR prevents removing the data dir if the member remove wasn't successful - we want these two operations to happen together. It also means that if node attempts to rejoin a cluster after it's left it won't use itself as a joining peer even if it is in etcd_cluster.
Note - we can still have situations where a node is corrupted, it leaves and rejoins the etcd cluster, but it's old enough that none of the values it has in the etcd_cluster in local_config is valid anymore. I'm not fixing this in this PR,
> [Reviewer: Rob] Tie removing the data dir and removing from cluster together

- debian/clearwater-etcd.init.d
This means we can modify shared_config without needed to know the local IP address.
I've not changed `advertise_peers` since that is used by other `etcd`s to reach this one (so `0.0,0,0` would be a __bad__ idea :grin:).
> [Reviewer Ellie] Allow clients to connect over localhost

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/check_config_sync
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/restore_config
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
As requested in https://github.com/Metaswitch/clearwater-etcd-plugins/pull/11
I've also fixed the restore_config script erroneously using -x.
Tested live on a sprout node.
> [Reviewer: EM] Unify root permission checking

- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/modify_nodes_in_queue.py
- Removed "Detailed output being sent to /.../queue_operation.log" message that showed up (twice) every time upload_shared_config was executed.
- Tidied up some weird line spacing
- Fixed queue_operation.log timestamps - they printed the milliseconds twice.
> [Reviewer: Ellie] Fixes related to queue_operation.log

- debian/clearwater-etcd.init.d
This takes the explicit "stop daemon" call out of the do_decommission method in /etc/init.d/clearwater-etcd.  The reasoning here is that the preceding etcdctl member remove will do this for us, and doing the explicit duplicate stop occasionally leads to spurious "can't stop daemon" errors that potentially confuse users (and might persuade them that the decommission has failed when it hasn't).
Tested on each of ralf, homestead and sprout nodes, in each case verifying that the clearwater-etcd daemon had stopped after the decommission.
> [Reviewer AJH] Don't explicitly stop etcd daemon after local member removed

- cluster_mgr_setup.py
- config_mgr_setup.py
- fvtest_setup.py
- queue_mgr_setup.py
- shared_setup.py
python-etcd requires urllib3 > 1.7. If we pull urllib3 1.18.1, the build fails due to https://github.com/shazow/urllib3/issues/986.
To avoid this, and future issues, pin urlib3 1.17 which is known to work.
> [Reviewer: Ellie] Pin urllib3 to 1.17 to prevent build failure

- clearwater-etcd/usr/share/clearwater/bin/get_etcd_initial_cluster.py
When we try and join the etcd cluster (not as a founding member), we query the subset of nodes in the etcd_cluster parameter to get the full list of nodes in the etcd cluster. If the first entry fails because etcd is down, then this throws a socket error which we weren't catching. This then meant that we tried to start etcd with the parameters `--initial-cluster "" --initial-cluster-state existing`, which etcd then barfed on.
Fixes #346
> [Reviewer: Graeme] Catch more exceptions

- src/metaswitch/clearwater/plugin_tests/test_cassandra_failed_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_cassandra_plugin.py
Add `mock_open.assert_called_once_with(plugin.files(), "r")` as in the other tests e.g. https://github.com/Metaswitch/clearwater-etcd/blob/dev/src/metaswitch/clearwater/plugin_tests/test_shared_config_plugin.py#L63
so that `make verify` passes.
> [Reviewer: AJL] Fix 'make verify'

- src/metaswitch/clearwater/plugin_tests/test_cassandra_plugin.py
Both `make verify` and the tests pass now.
`on_leaving_cluster` doesn't call `open` so I've deleted `mock_open` for that bit.
> [Reviewer: AJL] Do it properly this time

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/log_shared_config.py
This PR adds a check that we've got old and new shared config before attempting to log them to syslog. 
Tested live (checking that adding/updating shared_config doesn't give any error messages, and logs useful output to the screen/syslog).
Fixes https://github.com/Metaswitch/clearwater-etcd-plugins/issues/16
> [Reviewer: Richard] Recover when the shared_config key is empty

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
Sort the keys when displaying the cluster state so they are shown in a consistent order.
Tested live.
> [Reviewer: Seb] Sort the keys before display

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-dns-configuration
Tested live. On file:
```
{
"hostnames": [
{
"name": "<hostname 1>",
"records": [{"rrtype": "CNAME", "target": "<target for hostname 1>"}, {"rrtype": "CNAME", "target": "<target for hostname 1>"}]
},
{
"name": "<hostname 2>",
"records": [{"rrtype": "CNAME", "target": "<target for hostname 2>"}]
}
]
}
```
It prints out:
```
Name: <hostname 1>
Records:
rrtype: CNAME, target: <target for hostname 1>
rrtype: CNAME, target: <target for hostname 1>
Name: <hostname 2>
Records:
rrtype: CNAME, target: <target for hostname 2>
```
It supports multiple records, should we choose to implement that at a later stage. 
It also currently polices records being CNAME records, as this is all we support at the moment. If rrtype is not CNAME, it will print a helpful error message.
I'm going to update all the …
> [Reviewer: Ellie] Adds pretty print for dns_config

- cluster_mgr_setup.py
- config_mgr_setup.py
- plugins_setup.py
- queue_mgr_setup.py
- shared_setup.py
Move to use pyzmq 16.0.2, as this doesn't give us the warning text when upgrading clearwater-etcd. I've done some kick the tyres testing and this doesn't break anything. 
Fixes #258 
I'll update everything else that uses pyzmq as well.
> [Reviewer: Seb] Use pyzmq 16.0.2

- shared_setup.py
- src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
This PR patches python-etcd to catch MaxRetryErrors when we're waiting on a key. Tested live.
Fixes #324
> [Reviewer: Seb] Convert MaxRetryErrors to WatchTimeout errors

- clearwater-cluster-manager.root/usr/share/clearwater/conf/clearwater-cluster-manager.monit
- clearwater-config-manager.root/usr/share/clearwater/conf/clearwater-config-manager.monit
Move to using a group for the cluster/config managers, to make it consistent with the queue-manager/etcd.
> [No reviewer] Use group for cluster/config managers

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/upload_shared_config
This PR implements an infrastructure that allows an integrator (and potentially Project Clearwater itself at some point in the future) to supply a config validation script that will be run when shared_config is uploaded.  Such a script could, for example, check that the user has not changed any config parameters whose values must take mandatory values in a given deployment, or verify that any hostnames in the configuration can be resolved as expected in DNS.
Under this PR, upload_shared_config looks for executable files in /usr/share/clearwater/clearwater-config-manager/scripts/config_validation and runs them, interpreting any non-zero exit code as meaning "config has failed validation".  It its the responsibility of the script to echo/print any error details to STDOUT - these will appear …
> [Reviewer EM] Call validation checking scripts before uploading shared config

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-bgcf-configuration
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-dns-configuration
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-enum-configuration
- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-s-cscf-configuration
For each pretty-print script for the plugin config files, prints `Configuration file is present, but contains no entries`, followed by the expected format, if the file present is the default template.
> [No reviewer] Print expected format if config files present but empty

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_chronos_cluster.py
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_memcached_cluster.py
- debian/clearwater-etcd.init.d
This PR updates the load_from scripts so that they can be run on unstable clusters, and makes them use the run-in-signaling-namespace script. It also removes the force* options from etcd; these are no longer supported.
This PR is part of the work to fix up the etcd recovery process after loss of quorum - these changes have been live tested as part of that work.
> [Reviewer: Graeme] Update load_from scripts

- debian/clearwater-config-manager.install
This stops the dns_config_plugin being put in place, stopping us creating an unused config file.
This stops scripts such as check_config_sync reporting the config state, which might confuse users.
Tested live, and this seems to work fine. Just want you to have a quick look, in case you think this will somehow break other things.
My plan for merging will be as discussed:
* merge this into rel-114-fixes
* merge fixes down into dev
* revert the change as a new commit to merge into dev, so that we avoid conflicts down the line as much as possible
Sound reasonable?
> [Reviewer: Ellie] Do not install dns_config_plugin

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/print-s-cscf-configuration
Fixup expected format to be correct, and match http://clearwater.readthedocs.io/en/stable/Manual_Install.html#i-cscf-configuration.
> [No reviewer] Fixup printout of expected format

- debian/clearwater-cluster-manager.links
- debian/clearwater-config-manager.links
- debian/clearwater-queue-manager.links
This PR links puts commonly used Clearwater erscripts in the path in order to remove the need for long paths to be entered every time they're run: its often hard to remember where some of these regularly used scripts live, and tedious to type the full out every time when you do.
AJH recommended the approach of linking scripts explicitly from /usr/bin, rather than explicitly changing the path, as the latter is an "unfriendly" approach to the problem (path changes in packages are generally deprecated) and explicit links give us more control over scripts that users should run as opposed to internal scripts/executables that are not formally part of the user interface.  We agreed that I should add "cw-" to the front of the script names to minimise the chance of clashing with 3rd party packages …
> [Reviewer EM] Add /usr/bin links to commonly used scripts

- src/metaswitch/clearwater/plugin_tests/test_cassandra_plugin.py
Remember, you asked for these...
As the per commit messages:
* first commit is purely refactoring, not adding/changing tests. This means that adding the new tests doesn't mean adding loads of lines of copy-paste boiler plate setup.
* second commit is the main chunk. It adds the mock_exists class to be used as a side_effect in the unit tests. It takes a list of flags (files) that exist on the hypothetical test system, and then when called as the side effect of mocked os.path.exists returns true/false correctly.
* third commit is just a small change to go along with a markup to the actual plugin
Tests also pass verify and coverage :smiley:
> [Reviewer: Ellie] Cassandra uts

- clearwater-etcd/usr/share/clearwater/bin/poll_etcd_cluster.sh
- clearwater-etcd/usr/share/clearwater/bin/raise_etcd_cluster_alarm.sh
- clearwater-etcd/usr/share/clearwater/conf/clearwater-etcd.monit
- debian/clearwater-etcd.postinst
- debian/clearwater-etcd.prerm
We should only alarm once we've had 2 consecutive errors (like we do for some
other poll scripts).
This is a fix for issue #407, because we believe that we get false positives from the poll_etcd_cluster script when the cluster is actually healthy.
- live tested (by manually altering the poll_etcd_cluster script to return various errors)
> [Reviewer: Ellie] Less aggresssive alarms from poll_etcd_cluster.sh

- debian/control
I spotted that we were installing these packages, and they're unnecessary - we don't compile anything at install time so don't need header files.
> [Reviewer: Adam] Remove *-dev packages as install-time dependencies

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/log_shared_config.py
- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Use encoding to handle non-ascii characters. Each commit fixes one issue. Tested by looking at config manager log in live system. Unfortunate white space but didn't want to change git history again....
> Non ascii config

- debian/control
clearwater-etcd depends on python-common which requires libffi-dev to build the egg.
> [Reviewer: Seb] Document libffi-dev build dependancy

- clearwater-etcd/usr/share/clearwater/bin/poll_etcd_cluster.sh
- debian/clearwater-etcd.init.d
Save the healthy member list as just the list, and set etcd_cluster or
etcd_proxy to tat list depending on the node settings
Fix for issue: https://github.com/Metaswitch/clearwater-issues/issues/2094
> [Reviewer: Richard] Don't assume all nodes are etcd members as opposed to proxies

- debian/clearwater-etcd.init.d
This fixes https://github.com/Metaswitch/clearwater-issues/issues/2095
Note: you can still see an error message if you have only a single etcd master node in your cluster, and you try to restart the etcd service on that master node. This is because the only IP address it will have is its own, and it won't add that as a peer, and so won't be able to connect to get the member list.
However, if you've only got one etcd master node left, you've got bigger problems, as you should always have at least 3 master nodes (your 3 Vellum nodes if you have them, else all your nodes).
> [Reviewer: Richard] use etcd_proxy if it's specified, not etcd_cluster

- debian/clearwater-config-manager.init.d
- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/config_manager/main.py
- src/metaswitch/clearwater/queue_manager/main.py
Fixes 1480 by adding a TERM handler for the queue manager (and config manager). This means that we don't just kill queue manager when stopping it and let it shut down properly which means we can log that it's been stopped. I needed to extend the timeout for config manager so that we had enough time to unload all the plugins.
Queue manager and config manager don't use the QUIT handler since they can't receive the QUIT signal.
Tested live that shutdown logs are written to the log file.
> [Reviewer: EM] Improve queue manager shutdown logging

- debian/clearwater-etcd.init.d
This adds logs (which go to /var/log/syslog) for various etcd errors on startup
> [Reviewer: Adam] Add syslogs for etcd errors on startup

- clearwater-etcd/usr/share/clearwater/bin/poll_etcd_cluster.sh
Avoids the case where we store an empty list of healthy members which means we can't subsequently join the etcd cluster.
> [Reviewer: EM] Only store off healthy etcd members if some exist

- cluster_mgr_setup.py
- config_mgr_setup.py
- queue_mgr_setup.py
- shared_setup.py
I removed the dependencies which are in python-common.
I also removed the dependencies in the individual setup files which were also in the shared_setup.py file.
I then added downstream dependenices, which I found using the console output from the build server, and also by seeing what packages were present in the .eggs directory created when the repo is made.
I pinned the python packages to the versions on the build server.
For urllib3, two versions were originally installed. (1.17 and 1.21.1). I chose to pin to the most recent version.
I've spun up a deployment including these changes using chef, and it build correctly.
> Pin python dependencies in clearwater-etcd

- fvtest_setup.py
- plugins_setup.py
Not getting reviewed - since this is the equivalent of another reviewed request: https://github.com/Metaswitch/clearwater-etcd/pull/447/files.
The only additional change is pinning urllib3 to 1.21.1, not 1.21.2.
> pin with right version of urllib3

- clearwater-etcd/etc/logrotate.d/clearwater-etcd
- debian/clearwater-etcd.init.d
Ellie, please can you review this PR that adds some extra logging to the clearwater-etcd init.d script?
There is a new logfile, `/var/log/cleawater-etcd/clearwater-etcd-initd.log` which is managed by logrotate. The initd script logs the following to this file:
* Anything it would print to screen 
* Details about every etcdctl command specifically the command line that was run, the stdout and stderr, and the status code. 
* Some extra "signposting" logs that I've added to make the log files more readable. 
Other than the new logging I've not changed the external behaviour of the init.d script. This means for example that the stdout and stderr of various etcdctl commands still appears in the console, but I think that fixing that up is out of scope for this change.
> Add logs to the init.d script

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
Update the format and information for check_cluster_state by:
1. Remove node type as all clusters are currently associated with Vellum/SCN
2. Print IP and clusters for local node
This script prints the status of the Chronos, Memcached and Cassandra clusters.
This node (10.0.236.236) should not be in any cluster.
Describing the Chronos cluster:
The cluster is stable
10.0.8.175 is in state normal
Describing the Memcached cluster:
The cluster is stable
10.0.8.175 is in state normal
Describing the Cassandra cluster:
The cluster is stable
10.0.8.175 is in state normal
This script prints the status of the Chronos, Memcached and Cassandra clusters.
This node (10.0.8.175) should be in cassandra, chronos and memcached cluster.
Describing the Chronos cluster:
The cluster is stable
10.0.8.175 is in …
> [Reviewer: Ellie] Add information for check_cluster_state

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
This script prints the status of the Cassandra, Chronos, and Memcached clusters.
This node (10.0.102.12) should be in the Cassandra, Chronos and Memcached clusters.
Describing the Cassandra cluster:
The cluster is stable
10.0.102.12 is in state normal
10.0.95.164 is in state normal
10.0.144.57 is in state normal
Describing the Chronos cluster:
The cluster is stable
10.0.102.12 is in state normal
10.0.95.164 is in state normal
10.0.144.57 is in state normal
Describing the Memcached cluster:
The cluster is stable
10.0.102.12 is in state normal
10.0.95.164 is in state normal
10.0.144.57 is in state normal
> Always print clusters in alphabetic order.

- src/metaswitch/clearwater/cluster_manager/alarms.py
- src/metaswitch/clearwater/queue_manager/alarms.py
This raises the alarms logs to INFO level. This matches how we log alarms in the other components, it's not spammy given it's only when the alarm is raised/cleared by the queue/cluster manager (not the alarm manager resending alarms), and it's useful information to always have in the logs.
> [Reviewer: Sathiyan] Increase log level for alarms

- src/metaswitch/clearwater/cluster_manager/main.py
- src/metaswitch/clearwater/config_manager/main.py
- src/metaswitch/clearwater/queue_manager/main.py
This is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2309
We must not start them until we've set up the SIGTERM handler, else an early exception in one of the threads won't trigger the cluster/queue/config manager process to exit.
* tested live that adding a wait before installing the SIGTERM handler and starting the threads hit the issue before and doesn't now
* `make verify` , `make test` and `make fvtest` all pass
> [Reviewer: Richard] Delay starting the plugin threads

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py
- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Use subprocess.call with shell="True" risks command injection. 
As part of security check using Bandit, replace all such calls and os.system(command_string) calls with subprocess.call with shell=False (default option, hence not shown in the code). Without shell:
* Command needs to be passed in as a list rather than string literal. shlex.split splits up command string into list of command line argument.
* Pipe symbol no longer works, use subprocess.PIPE to store output of first command and pass into second command
https://security.openstack.org/guidelines/dg_avoid-shell-true.html
(to show the new code works)
1.  Create a Chef deployment using new code and then resize it. 
2.  Cluster manager will kick off etcd and uses new code.
3.  Run live tests and check they pass.
(why new code is more …
> [Reviewer: Krista] Use subprocess call without shell

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
Unfortunately the "Usage" statement for all the scripts uses [] to indicate a variable, rather than an optional variable. Since there's no precedent for how to describe optional variables, I chose the approach of two different usage statements.
This is required for DM. This implies that we support not using the local etcd client when marking node failed.
> Allow an optional etcd IP to be passed to mark_node_failed

- Makefile
New python.mk file is added to run Bandit analysis on python code and print high severity issues -
https://github.com/Metaswitch/clearwater-build-infra/pull/64
This pull request pass in EXCLUDE_LIST and include that analysis as part of make deb. Similar action has been taken for the following repository:
https://github.com/Metaswitch/clearwater-infrastructure/pull/478
https://github.com/Metaswitch/clearwater-craft/pull/83
...(TBD)
Tested by ```make analysis``` and getting:
```
/home/ubuntu/clearwater-etcd/_env/bin/easy_install bandit
Searching for bandit
Best match: bandit 1.4.0
Processing bandit-1.4.0-py2.7.egg
bandit 1.4.0 is already the active version in easy-install.pth
Installing bandit script to /home/ubuntu/clearwater-etcd/_env/bin
Installing bandit-baseline script to …
```
> [Reviewer: KH1] Run Bandit analysis from python.mk as part of build process

- Makefile
Reverts Metaswitch/clearwater-etcd#473
Revert due to accidentally committing changes in submodules
> Revert "[Reviewer: KH1] Run Bandit analysis from python.mk as part of build process"

- Makefile
Re-commit of https://github.com/Metaswitch/clearwater-etcd/pull/473, which was reverted due to accidentally committing changes in submodules.
> Bandit check as part of build

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
Testing done:
```
[scn]clearwater@scn-1:~$ sudo cw-mark_node_failed "scn" "memcached" 173.16.1.49
Detailed output being sent to /var/log/clearwater-etcd/mark_node_failed.log
Marking node as failed and removing it from the cluster - will take at least 30 seconds
Process complete - 173.16.1.49 has left the cluster
[scn]clearwater@scn-1:~$ sudo cw-mark_node_failed "scn" "memcached" 173.16.1.49
Detailed output being sent to /var/log/clearwater-etcd/mark_node_failed.log
Not in cluster - no work required
[scn]clearwater@scn-1:~$ sudo cw-mark_node_failed "scn" "memcached" 1.2.3.4
Detailed output being sent to /var/log/clearwater-etcd/mark_node_failed.log
Not in cluster - no work required
[scn]clearwater@scn-1:~$ /usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state
This …
```
> Mark node failed ignore if not in cluster

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed
The code "worked", but `set -u` was throwing up errors to do with unset variables, and `set -e` was causing the script to crash, so I've jiggled things around.
Have tested calling mark_node_failed with the following combinations being set:
- local_ip
- local_ip, etcd_ip
- local_ip, management_local_ip, etcd_ip
- local_ip, management_local_ip
Not exhaustive, but close enough.
> Fix up mark_node_failed for when management_local_ip is unset

- src/metaswitch/clearwater/plugin_tests/test_apply_chronos_shared_config_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_apply_config_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_cassandra_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_chronos_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_chronos_shared_config_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_dns_json_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_fallback_ifcs_xml_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_memcached_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_shared_config_plugin.py
- src/metaswitch/clearwater/plugin_tests/test_shared_ifcs_xml_plugin.py
As run_command now takes an array of arguments rather than a command string
> Fix mock calls to run_command in UT

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
- src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
Ellie - please can you review this (I'm picking on you, because you recently reviewed a fix in a similar area from CC3).
This is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2351
Now we check to ensure that we can contact etcd before we try to mark a node as failed, improving error output.  I've also reduced the default timeout, as it seemed unnecessary for this command to wait four minutes before reporting failure (4 retries @ 60 seconds).
Testing-wise, I've verified this by passing in a bad etcd IP address, and ensuring that we get a timeout, and an error response.
> [Reviewer: EM] Check for etcd connection on mark_node_failed

- src/metaswitch/clearwater/cluster_manager/synchronization_fsm.py
This made it a lot harder to debug as we don't currently get stacktraces 😞 .
`make verify test` passes, and I've confirmed the fix is good live.
> [Reviewer: Ellie] Log exception as exceptions

- src/metaswitch/clearwater/etcd_shared/plugin_utils.py
Prepend the command args with the namespace args if we're using the signaling namespace (the previous code set command_args to None).
I've not tested live as I've got no easy way of getting a system with signaling namespace. I've tested the python change in isolation.
> [Reviewer: Krista] Extend command args

- debian/clearwater-etcd.init.d
On the dogfood system i was seeing etcd fail to start, logging out that i needed to specify either etcd_cluster or etcd_proxy. From that i worked out that we must have been checking the healthy_member_list file, and finding something, but that the something was blank. Double checking on the system, and sure enough the file was present but empty.
I'm not sure how we got into that state, but this PR adds a step to verify that what we get from the healthy members list is not just blank space. I've also added a bit more in the way of comments, so hopefully it's a bit clearer in future.
To test the bash, i ran the following in my shell:
```
$ healthy_cluster="asd  123"
$ if [[ -z "${healthy_cluster// /}" ]]; then echo hello; fi
$ healthy_cluster="   "
$ if [[ -z "${healthy_cluster// /}" ]]; …
```
> [Reviewer: Seb] Improve init checking of healthy_cluster_view

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
for the node to be removed from the Consul backend. Exits with 1 return
value on timeout, or if the value is anything other than "finished"
> Mark node failed now waits for 10 minutes

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
This fixes the output of  check_cluster_state to ignore empty keys and to not mention Cassandra. I've also removed some dead code (etcd_version, remote memcached plugin).
Tested live.
Output before fix:
```
This script prints the status of the Cassandra, Chronos, and Memcached clusters                                                                                                                                                              in the local site (gdc).
This node (10.225.167.115) should not be in any cluster.
Describing the Cassandra cluster:
The cluster is stable
Describing the Chronos cluster:
The cluster is stable
10.225.167.114 is in state normal
Describing the Memcached cluster:
The cluster is stable
10.225.167.114 is in state normal
```
Output after fix:
```
This script …
```
> [Reviewer: Krista] Fix up output to remove Cassandra

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/mark_node_failed.py
- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/modify_nodes_in_queue.py
The way we set up logging in the modify_nodes_in_queue script meant we were using the localtime rather than UTC. This was dumb, given the log format includes the string `UTC` after the time stamp.
Set up a node in a different time zone:
```
[vellum-1]ubuntu@ec2-54-158-150-74:~$ sudo dpkg-reconfigure tzdata
Current default time zone: 'Asia/Kuwait'
Local time is now:      Thu Sep 21 19:55:07 AST 2017.
Universal Time is now:  Thu Sep 21 16:55:07 UTC 2017.
```
Prior to the changes, you'd see the following output:
```
[vellum-1]ubuntu@ec2-54-158-150-74:~$ sudo cw-upload_shared_config && tail -n 4 /var/log/clearwater-queue-manager/queue_operation.log
Validating /etc/clearwater/shared_config
Validation of /etc/clearwater/shared_config succeeded
No changes detected in shared configuration file …
```
> [Reviewer: Richard] Set up queue-mgr logging to use gmtime, not localtime

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
This made sure the check_cluster_state script returned a value when it was run. This allows an error value of 1 to be returned when the clusters are not stable. Or 1 to be returned when stable.
> Fixing issue 2400

- src/metaswitch/clearwater/plugin_tests/test_memcached_plugin.py
Includes the submodule commit which actually removes the file, and changes to remove the tests associated with it. 
`make test` and `make verify` pass fine, and as this is just tidying up removal of bad code, i don't think we really need further testing than that.
> [Reviewer: Richard] Remove remote memcached plugin

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/check_cluster_state.py
We specify the local site name on running the script, and i believe we don't run any plugins with anything other than the default site name. 
This just  uses local_site where we would otherwise have used the key site name, or a blank string.
> [Reviewer: Richard] Fix site name printing

- .gitignore
- Makefile
Changes to use the common python build infrastructure defined by https://github.com/Metaswitch/clearwater-build-infra/pull/69
I've had to define a macro here which we use for each of the queue-, cluster- and config-managers.
Requires the changes to python-common in: https://github.com/Metaswitch/python-common/pull/115 too
> [Reviewer: Richard] Common build infra

- src/metaswitch/clearwater/config_manager/move_config.py
This should sort out the call to `nc` so that it works properly.
> Fixing call to `nc`

- src/metaswitch/clearwater/config_manager/move_config.py
We weren't returning the correct file location for the revision index file.
(I also touched up one of the exception texts while I was at it)
> Fixing bug in revision index file location code

- README.md
We moved to V3.1.7 in May - moving over readme file.
> Correct version number in etcd readme

- clearwater-config-manager.root/etc/rsyslog.d/35-config-manager.conf
The syslog configuration file for clearwater-config-manager contained two syntax errors and a bug:
* An extra comma
* An unnecessary colon before the `stop` command
* A missing `&` before the stop command, meaning that no further processing would happen after this file - and preventing anything from being written to `/var/log/syslog`.
I've checked that this new version passes rsyslogd's config validation using `rsyslogd -N 1`.
> Fix up syntax of Syslog Configuration

- src/metaswitch/clearwater/config_manager/config_access.py
- src/metaswitch/clearwater/config_manager/test/test_config_access.py
Previously, if you ran cw-config via the console it didn't work. This is because `who am i` returns nothing in this circumstance. This change fixes that edge case.
I've tested this by running it with chef (which runs `cw-config` from the console). It works! Also added UT coverage for the new code.
> [Reviewer: MD6] Fixes cw-config to handle being run via console

- src/metaswitch/clearwater/config_manager/test/test_config_access.py
There's a `make verify` failure. We shouldn't have any of those.
> Fixing `make verify` failure

- clearwater-queue-manager.root/usr/share/clearwater/clearwater-queue-manager/scripts/check_node_health.py
Previously, it would always declare the node healthy after 30s. Now, it actually checks whether the node is healthy.
Changes:
* (the big one) `monit summary` commands *end* with the `Process` or `Program` word, doesn't start with it. Previously, we'd never notice any monit errors at all. This meant that this script was a glorified `sleep(30)` command
* I've added `Execution failed` as a CRITICAL error. This, I hope, is uncontroversial
* I've added `Wait parent` as a CRITICAL error. Possibly more controversial. Programs in `Wait parent` state would be started, but are currently blocked behind another process not being ready. I think this is sufficient to prevent us from declaring the node healthy and moving on to the next node in the restart queue.
Tested live on a node with Sprout …
> [Reviewer: Adam] check_node_health shouldn't just be a glorified sleep() call

- clearwater-config-manager.root/usr/share/clearwater/clearwater-config-manager/scripts/validate_json.py
The issue - we validate a schema which has duplicate keys.
For example, the below rph.json config file would be validated and uploaded:
```
{
"priority_blocks":[
{
"priority":1,
"priority":2,
"rph_values":["wps.0"]
}
],
"priority_blocks":[]
}
```
This isn't good. What is the priority of wps.0? 1? 2? Default?
We need to flag this error to the user, and prevent the upload.
There is not capability to prevent this in the schemas, so additional code is necessary.
The code I have added will prevent json files with duplicated keys from being validated, so their upload will be blocked.
I've tested this live, but haven't written any UTs (validate_json.py is not currently UTed, and this change wasn't big enough to merit adding a whole framework).
> Prevent json config files with duplicate keys being uploaded

- src/metaswitch/clearwater/config_manager/config_access.py
This changes has been made to avoid issues with non-ascii characters. This has mainly involved changes in the upload step especially with preparing for syslog, though one change has been made to the download step as well.
I have live tested this on a node on both shared_config and dns_json.
I'm just going to tag you in this @kenferguson as it was on top of your recent changes https://github.com/Metaswitch/clearwater-etcd/pull/544 if you are interested.
> Changes to config_access to allow non-ascii comments in the config

- src/metaswitch/clearwater/etcd_tests/etcdcluster.py
- src/metaswitch/clearwater/etcd_tests/etcdserver.py
- src/metaswitch/clearwater/etcd_tests/etcdtestbase.py
Hopefully this should give us a slightly better idea of what's going on if we hit errors in this area again. I think it must have been some weird interaction between different jobs on the build machine, though not sure what as you said it's all run isolated.
I forced the log out by removing the 'not', and it comes out as:
```
test_basic_clustering (metaswitch.clearwater.etcd_tests.etcdtestbase.EtcdTestBase) ...
s1: 127.0.0.148, isLeader False
s2: 127.0.0.149, isLeader True
ok
test_large_clusters (metaswitch.clearwater.etcd_tests.etcdtestbase.EtcdTestBase) ... ok
```
Not really sure we can do anything more on this atm, though open to suggestions of any more information that might be useful.
> [Reviewer: Richard] Log detail if test fails

- src/metaswitch/clearwater/config_manager/config_access.py
- src/metaswitch/clearwater/config_manager/config_type_class_plugin.py
- src/metaswitch/clearwater/config_manager/test/test_config_access.py
- src/metaswitch/clearwater/config_manager/test/test_config_type.py
This adds a way to print out any messages from successful validation and say which scripts have passed
Also changes the unit tests based on these changes.
I haven't done live testing of this for the configs other than shared_config which may cause it to change in the future if they over print to screen.
> Updates validate process during cw-config

- debian/clearwater-etcd.init.d
We saw an issue where two instances of etcd had been started on a node, causing chaos. This `start-stop-daemon ... --test` line is meant to prevent that, but it was using `--name clearwater-etcd` when the process's name is just `etcd`, so wasn't matching on the right process.
Looks like this has been in the code forever. (You're raising an issue so there's a record of it).
This change should fix it - I've tested that basename does the right thing:
```
13:56:11-rkd@abra:~/salinas$ echo $(basename /usr/share/clearwater/clearwater-etcd/3.1.7/etcd)
etcd
```
and I'll copy this init.d file onto a system and reboot to test it live before merging.
@eleanor-merry , any comments given your etcd experience?
> [Reviewer: MD6] Fix process name matching - 'etcd' not 'clearwater-etcd'

- debian/clearwater-queue-manager.postinst
With the new `cw-config` manager, the `queue_operation.log` file needs to be writable to `adm` users. On upgrade, the log file isn't writable.
I've tested by making the file non-writable, upgrading to this fix, and checking that the file is now writable.
> [Reviewer: Adam] Ensure queue_operation.log is writable on upgrade

- config_mgr_setup.py
- src/metaswitch/clearwater/config_manager/test/test_config_type.py
Seb,
This follows on from https://github.com/Metaswitch/clearwater-etcd/pull/554
This adds the required requirement in `setup.py` for jsonschema (required by `validate_json.py`), and fixes up the test to need the expected virtual environment.
> [Reviewer: Seb] Fix up etcd tests and requirements

- src/metaswitch/clearwater/config_manager/test/test_config_type.py
I've added a test where an error is thrown by the validation script, as this error branch wasn't tested otherwise.
> Add UT to reach full coverage on eMPS python work.

- src/metaswitch/clearwater/etcd_shared/common_etcd_synchronizer.py
#536 broke coverage in clearwater-etcd
This PR just acknowledges that explicitly by excluding the uncovered line.
> [No reviewer] Be explicit about missing coverage

- debian/clearwater-etcd.init.d
These are the logs I suggested in https://github.com/Metaswitch/clearwater-issues/issues/2883.
Tested live:
```
[scn]clearwater@grdeployment-site2-scn-2:~$ tail /var/log/clearwater-etcd/clearwater-etcd-initd.log
2018-01-15 18:06:42.367873180 [30851] Restarting etcd clearwater-etcd
2018-01-15 18:06:42.373201306 [30851] Configured ETCDCTL_PEERS: 10.1.4.130:4000,
2018-01-15 18:06:42.373820222 [30851] Check for previous failed startup attempt
2018-01-15 18:06:42.374754371 [30851] Running etcdctl member list
Failed to get leader:  client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member http://10.1.4.132:4000 has no leader
; error #1: client: etcd member http://10.1.4.130:4000 has no leader
; error #2: dial tcp 10.1.4.131:4000: getsockopt: connection refused …
```
> [Reviewer: Ellie] Add process ID to clearwater-etcd-initd.log

- debian/clearwater-etcd.init.d
Similar to https://github.com/Metaswitch/clearwater-etcd/pull/562, this improves the logging in the init script. Specifically, this logs out our process ancestors, e.g.
```
2018-01-15 18:55:22.469394237 [6364] Invoked with argument 'restart'
2018-01-15 18:55:22.473594571 [6364] Process tree:  init(1)---monit(1671)---bash(6360)---clearwater-etcd(6364)---pstree(6377)
```
I'm hoping this will prove my hypothesis that etcd sometimes gets started by monit and sometimes directly by upstart.
I'm merging without review to get in tonight's build.
> [Post-reviewer: EM] Log who called us - monit or upstart?

- debian/clearwater-etcd.init.d
I've copied the changes into a terminal to check they work:
```
[scn]clearwater@qa1-site1-scn-1:~$ NAME=clearwater-etcd
[scn]clearwater@qa1-site1-scn-1:~$ LOCKFILE_DIR=/var/run/$NAME
[scn]clearwater@qa1-site1-scn-1:~$ LOCKFILE=$LOCKFILE_DIR/$NAME-initd.lock
[scn]clearwater@qa1-site1-scn-1:~$ mkdir -p $LOCKFILE_DIR
[scn]clearwater@qa1-site1-scn-1:~$ echo $LOCKFILE_DIR
/var/run/clearwater-etcd
[scn]clearwater@qa1-site1-scn-1:~$ echo $LOCKFILE
/var/run/clearwater-etcd/clearwater-etcd-initd.lock
```
After creating that directory, etcd is starting on the node you pointed me at.
> [Reviewer: Seb] Create lockfile directory before locking

- src/metaswitch/clearwater/config_manager/alarms.py
Ellie,
Post trying to debug a config alarm on Friday, I've added a log line to config manager to log when we raise an alarm.
I'm fairly confident we won't just spam this, and will instead just notify when the reason for raising the alarm changes, or config manager restarts, so I think this is safe. I've tested the change in Chef.
Sample alarm text is:
```
29-01-2018 12:20:13.600 UTC WARNING alarms.py:48 (thread SharedIFCsXMLPlugin): Config not in sync - status: {'/etc/clearwater/bgcf.json': True, '/etc/clearwater/shared_ifcs.xml': True, '/etc/clearwater/shared_config': False, '/etc/clearwater/fallback_ifcs.xml': True, '/etc/clearwater/rph.json': True, '/etc/clearwater/s-cscf.json': True, '/etc/clearwater/dns.json': True, '/etc/clearwater/enum.json': True}
```
where `True` indicates a file …
> [Reviewer: Ellie] Log which files are causing config sync alarms

- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster
- clearwater-cluster-manager.root/usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster.py
The load_from_cassandra_cluster scripts require sudo. They shouldn't - an admin user should be allowed to run these scripts.
> [Reviewer: Sathiyan] Stop the load from cassandra scripts needing sudo

- src/metaswitch/clearwater/config_manager/config_access.py
- src/metaswitch/clearwater/config_manager/config_type_class_plugin.py
- src/metaswitch/clearwater/config_manager/test/test_config_access.py
- src/metaswitch/clearwater/config_manager/test/test_config_type.py
Currently, the `cw-config upload xxx` command collects the output of any validation scripts, and then prints it to the screen once all the validation scripts have run.
As per issue: https://github.com/Metaswitch/clearwater-issues/issues/3691, this can make it look like the config upload has hung, whereas it's actually just being slow.
This changes that so that we just allow all output to go to the screen as it's produced by the validation script. To do this, I've had to abandon collecting the output, but I don't think we lose very much by doing that, it just changes the formatting.
I've also had to fix up the UTs, one of which I've deleted as it wasn't doing anything new. I've also removed some expectations on number of logs written in the UTs, as I think that's a bad thing to do.
As an …
> [Reviewer: KAF] Progressive output config upload

- src/metaswitch/clearwater/config_manager/test/test_config_type.py
Test changes corresponding to: https://github.com/Metaswitch/clearwater-etcd-plugins/pull/60
`make full_test` passes, and I've live tested uploading valid rph_json and it works (and invalid rph_json is correctly rejected).
> [Reviewer: KAF] Fix up RPH config access plugin to use new interface

- debian/clearwater-etcd.init.d
Fixes https://github.com/Metaswitch/clearwater-issues/issues/3772 and https://github.com/Metaswitch/dudamel/issues/2369 by simply stopping proxy etcd instances during decommissioning rather than trying to go through the full member remove processing.
> Don't decommission proxy nodes
